name: base
channels:
- conda-forge
dependencies:
  - nodejs
  - ipympl
  - rise
  - pip:
      - autopep8
      - black
      - jupyterlab_code_formatter
      - jupyterlab-solutions
      - numecon
      - yapf
